apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: demo-flask-k8s
build:
  artifacts:
  - image: k3d-registry.localhost:12345/demo/todolist
    docker:
      dockerfile: Dockerfile
  insecureRegistries:
  - k3d-registry.localhost:12345
  local:
    push: false

deploy:
  kustomize:
    paths:
      - k8s/overlays/local/
