apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
# - github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6

namespace: demo-flask-prod
namePrefix:

patchesStrategicMerge:
- flask-hpa-prod.yaml