apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - tools/pgadmin.yaml

namespace: default
namePrefix: local-
configMapGenerator:
  - name: config-map-kustomize
    env: config.properties

images:
- name: ghcr.io/tom333/demo_flask_k8s:main
  newName: k3d-registry.localhost:12345/demo/todolist


replicas:
- name: flask-backend-deployment
  count: 1

patchesStrategicMerge:
- flask-hpa-staging.yaml

