apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: demo-flask-local
namePrefix: local-
configMapGenerator:
  - name: config-map-kustomize
    env: config.properties

images:
- name: flask-app
  newName: registry.matrix/demo_flask_k8s
  newTag: latest

replicas:
- name: flask-backend-deployment
  count: 1

patchesStrategicMerge:
- flask-hpa-staging.yaml