apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
  labels:
    app: flask-backend
spec:
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: ghcr.io/tom333/demo_flask_k8s:main
          resources:
            requests:
              cpu: "50m"
              memory: "128M"
            limits:
              cpu: "500m"
              memory: "512M"
          env:
            - name: SERVICE_POSTGRES_SERVICE_HOST
              value: local-service-postgres
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: POSTGRES_DB_PSW
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config-map-kustomize