apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
spec:
  template:
    spec:
      containers:
        - name: flask-app
          imagePullPolicy: Always
          image: ghcr.io/tom333/demo_flask_k8s:main
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: SERVICE_POSTGRES_SERVICE_HOST
              value: service-postgres.demo-flask.svc.cluster.local
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: POSTGRES_DB_PSW
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: config-map-kustomize