apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  labels:
    app: flask-backend
spec:
  ports:
  - port: 8000
    targetPort: 80
    name: http
  selector:
    app: flask-backend