apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: demo-flask-staging
namePrefix: staging-
configMapGenerator:
  - name: config-map-kustomize
    env: config.properties

replicas:
- name: flask-backend-deployment
  count: 1

patchesStrategicMerge:
- flask-hpa-staging.yaml